# Generated by Django 4.1.4 on 2022-12-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
